
workflows:
    ionic-capacitor-android-app: 
        name: Ionic App 
        triggering: 
          events: 
            - push 
          branch_patterns: 
            - pattern: '*' 
              include: true 
              source: true 
        environment: 
            node: latest 
            groups:  
              - dev 
        scripts: 
            - npm install   
            - npm run build    
            - npx cap sync android
            - | 
                # build Android 
                cd android 
                ./gradlew assembleDebug   
        
        artifacts: 
            - android/app/build/outputs/**/*.apk 
        publishing:             
          scripts: 
              - chmod +x ./telegram.sh
              - bash ./telegram.sh $CHATID $APP_TOKEN ./android/app/build/outputs/apk/**/*